#!/usr/bin/env python3
"""
Generate Release Notes

Creates release notes from training report for GitHub Releases.
"""

import json
import os
from datetime import datetime


def main():
    # Load training report
    report_path = "training_report.json"
    if not os.path.exists(report_path):
        print("ERROR: No training report found")
        # Create minimal release notes
        release_notes = """# Model Training Run

No training results available.
"""
        with open("release_notes.md", "w") as f:
            f.write(release_notes)
        return

    with open(report_path, "r") as f:
        report = json.load(f)

    # Generate release notes
    latest_set = report.get("latest_set", "Unknown")
    timestamp = report.get("timestamp", "")
    training_date = timestamp[:10] if timestamp else datetime.now().strftime("%Y-%m-%d")

    release_notes = f"""# Model Release - {latest_set}

**Training Date:** {training_date}

## Training Results

"""

    training_results = report.get("training_results", [])
    if training_results:
        release_notes += "| Model | Accuracy | Training Picks | Validation Picks | Epochs |\n"
        release_notes += "|-------|----------|----------------|------------------|--------|\n"

        for result in training_results:
            model_name = result.get("experiment_name", "Unknown")
            accuracy = result.get("validation_accuracy", 0.0)
            training_picks = result.get("training_picks", 0)
            validation_picks = result.get("validation_picks", 0)
            epochs = result.get("num_epochs", 0)

            release_notes += f"| {model_name} | {accuracy:.2f}% | {training_picks:,} | {validation_picks:,} | {epochs} |\n"
    else:
        release_notes += "No models were trained in this run.\n"

    release_notes += "\n## Data Updates\n\n"

    updates = []
    if report.get("cards_updated"):
        updates.append("Cards database updated for new set")
    if report.get("premier_updated"):
        updates.append("Premier Draft data updated")
    if report.get("traditional_updated"):
        updates.append("Traditional Draft data updated")
    if report.get("picktwodraft_updated"):
        updates.append("PickTwoDraft data updated")

    if updates:
        for update in updates:
            release_notes += f"- {update}\n"
    else:
        release_notes += "No data updates in this run.\n"

    release_notes += "\n## Files Included\n\n"
    release_notes += "This release contains:\n"
    release_notes += "- PyTorch models (`.pt` files) - For training and evaluation\n"
    release_notes += "- ONNX models (`.onnx` files) - For web deployment\n"

    release_notes += "\n---\n\n"
    release_notes += "*Automatically generated by nightly training workflow*\n"

    with open("release_notes.md", "w") as f:
        f.write(release_notes)

    print("Generated release notes")
    print("\n" + "="*50)
    print("RELEASE NOTES PREVIEW")
    print("="*50)
    print(release_notes)
    print("="*50 + "\n")


if __name__ == "__main__":
    main()
